language: node_js
node_js:
  - 'lts/*'
git:
  depth: 5
  quiet: true
before_install:
  - sudo apt-add-repository --yes --update ppa:ansible/ansible
  - sudo apt-get install -y python-minimal python-pip python-boto software-properties-common ntp unzip build-essential ansible python3-pip
  - sudo pip install boto boto3  
addons:
  apt:
    update: true
script: ansible-playbook -c local install-nginx.yaml
deploy:
  skip_cleanup: true
  provider: script
  script: ansible-playbook -c local zdt.yaml --extra-vars "VNET_NAME=cloudexdemo"
  on:
    branch: master
notifications:
  email:
    - muyiwa@tssdevs.com
